import type {
  Institution,
  Student,
  Parent,
  ParentStudent,
  Staff,
  AcademicYear,
  Term,
  Class,
  Stream,
  Subject,
  ClassSubject,
  AttendanceSession,
  AttendanceRecord,
  Exam,
  StudentMark,
  GradingSystem,
  FeeStructure,
  StudentInvoice,
  Payment,
  Receipt,
  AuditLog,
  AuthUser,
} from '@/types'

export const DEMO_INSTITUTIONS: Institution[] = [
  {
    id: 'inst-001',
    name: 'Kampala Model High School',
    code: 'KMHS-256',
    type: 'secondary',
    logo_url: '',
    address: 'Plot 42, Kira Road, Kamwokya, Kampala',
    phone: '+256 772 123456',
    email: 'info@kampalamodel.sc.ug',
    website: 'https://kampalamodel.sc.ug',
    country: 'Uganda',
    region: 'Central',
    district: 'Kampala',
    motto: 'Strive for Excellence and Integrity',
    subscription_plan: 'professional',
    subscription_status: 'active',
    settings: {
      currency: 'UGX',
      date_format: 'dd/MM/yyyy',
      modules_enabled: ['students', 'parents', 'staff', 'classes', 'subjects', 'attendance', 'exams', 'fees', 'reports', 'settings', 'audit', 'announcements'],
      enable_streams: true,
      enable_health_module: true,
      enable_library: true,
      enable_inventory: true,
      enable_parent_portal: true,
      enable_student_portal: true,
      academic_structure: {
        class_levels: [
          { id: 's1', name: 'Senior 1 (S1)', order: 1, section: 'O-Level' },
          { id: 's2', name: 'Senior 2 (S2)', order: 2, section: 'O-Level' },
          { id: 's3', name: 'Senior 3 (S3)', order: 3, section: 'O-Level' },
          { id: 's4', name: 'Senior 4 (S4)', order: 4, section: 'O-Level' },
          { id: 's5', name: 'Senior 5 (S5)', order: 5, section: 'A-Level' },
          { id: 's6', name: 'Senior 6 (S6)', order: 6, section: 'A-Level' },
        ],
        uses_streams: true,
        uses_departments: true,
        uses_combinations: true,
      },
    },
    created_at: '2025-01-10T08:00:00Z',
    updated_at: '2026-08-20T10:00:00Z',
  },
  {
    id: 'inst-002',
    name: 'St. Bernadette Institute of Health Sciences',
    code: 'SBIHS-04',
    type: 'nursing',
    logo_url: '',
    address: 'Mbarara-Masaka Highway, Mbarara City',
    phone: '+256 701 987654',
    email: 'admin@stbernadette.ac.ug',
    website: 'https://stbernadette.ac.ug',
    country: 'Uganda',
    region: 'Western',
    district: 'Mbarara',
    motto: 'Healing with Compassion and Skill',
    subscription_plan: 'enterprise',
    subscription_status: 'active',
    settings: {
      currency: 'UGX',
      date_format: 'dd/MM/yyyy',
      modules_enabled: ['students', 'parents', 'staff', 'classes', 'subjects', 'attendance', 'exams', 'fees', 'reports', 'settings', 'clinical_rotations'],
      enable_streams: false,
      enable_health_module: true,
      enable_library: true,
      enable_inventory: true,
      enable_parent_portal: false,
      enable_student_portal: true,
      academic_structure: {
        class_levels: [
          { id: 'cert1', name: 'Certificate in Nursing - Year 1', order: 1, section: 'Certificate' },
          { id: 'cert2', name: 'Certificate in Nursing - Year 2', order: 2, section: 'Certificate' },
          { id: 'dip1', name: 'Diploma in Midwifery - Year 1', order: 3, section: 'Diploma' },
          { id: 'dip2', name: 'Diploma in Midwifery - Year 2', order: 4, section: 'Diploma' },
          { id: 'dip3', name: 'Diploma in Comprehensive Nursing - Year 3', order: 5, section: 'Diploma' },
        ],
        uses_streams: false,
        uses_departments: true,
        uses_combinations: false,
      },
    },
    created_at: '2025-02-01T08:00:00Z',
    updated_at: '2026-08-20T10:00:00Z',
  },
  {
    id: 'inst-003',
    name: 'Little Angels Nursery & Junior School',
    code: 'LAN-01',
    type: 'nursery',
    logo_url: '',
    address: 'Muyenga Tank Hill Road, Kampala',
    phone: '+256 782 555444',
    email: 'hello@littleangels.co.ug',
    country: 'Uganda',
    region: 'Central',
    district: 'Kampala',
    motto: 'Nurturing Young Minds for a Brighter Future',
    subscription_plan: 'starter',
    subscription_status: 'active',
    settings: {
      currency: 'UGX',
      date_format: 'dd/MM/yyyy',
      modules_enabled: ['students', 'parents', 'staff', 'classes', 'attendance', 'fees', 'reports'],
      enable_streams: true,
      enable_health_module: false,
      enable_library: false,
      enable_inventory: false,
      enable_parent_portal: true,
      enable_student_portal: false,
      academic_structure: {
        class_levels: [
          { id: 'baby', name: 'Baby Class (Daycare/Creche)', order: 1, section: 'Early Childhood' },
          { id: 'middle', name: 'Middle Class', order: 2, section: 'Early Childhood' },
          { id: 'top', name: 'Top Class (Pre-Primary)', order: 3, section: 'Early Childhood' },
        ],
        uses_streams: true,
        uses_departments: false,
        uses_combinations: false,
      },
    },
    created_at: '2025-03-01T08:00:00Z',
    updated_at: '2026-08-20T10:00:00Z',
  },
]

export const DEMO_ACADEMIC_YEARS: AcademicYear[] = [
  {
    id: 'ay-2026',
    institution_id: 'inst-001',
    name: '2026 Academic Year',
    start_date: '2026-02-02',
    end_date: '2026-11-28',
    is_current: true,
    status: 'active',
    created_at: '2025-12-15T00:00:00Z',
  },
  {
    id: 'ay-2025',
    institution_id: 'inst-001',
    name: '2025 Academic Year',
    start_date: '2025-02-03',
    end_date: '2025-11-29',
    is_current: false,
    status: 'completed',
    created_at: '2024-12-15T00:00:00Z',
  },
]

export const DEMO_TERMS: Term[] = [
  {
    id: 'term-1-2026',
    institution_id: 'inst-001',
    academic_year_id: 'ay-2026',
    name: 'Term 1, 2026',
    type: 'term',
    start_date: '2026-02-02',
    end_date: '2026-05-02',
    is_current: true,
  },
  {
    id: 'term-2-2026',
    institution_id: 'inst-001',
    academic_year_id: 'ay-2026',
    name: 'Term 2, 2026',
    type: 'term',
    start_date: '2026-05-25',
    end_date: '2026-08-22',
    is_current: false,
  },
  {
    id: 'term-3-2026',
    institution_id: 'inst-001',
    academic_year_id: 'ay-2026',
    name: 'Term 3, 2026',
    type: 'term',
    start_date: '2026-09-14',
    end_date: '2026-11-28',
    is_current: false,
  },
]

export const DEMO_CLASSES: Class[] = [
  {
    id: 'cls-s1',
    institution_id: 'inst-001',
    academic_year_id: 'ay-2026',
    name: 'Senior One (S.1)',
    level: 1,
    type: 'O-Level',
    capacity: 120,
    created_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'cls-s2',
    institution_id: 'inst-001',
    academic_year_id: 'ay-2026',
    name: 'Senior Two (S.2)',
    level: 2,
    type: 'O-Level',
    capacity: 110,
    created_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'cls-s3',
    institution_id: 'inst-001',
    academic_year_id: 'ay-2026',
    name: 'Senior Three (S.3)',
    level: 3,
    type: 'O-Level',
    capacity: 100,
    created_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'cls-s4',
    institution_id: 'inst-001',
    academic_year_id: 'ay-2026',
    name: 'Senior Four (S.4 Candidates)',
    level: 4,
    type: 'O-Level',
    capacity: 95,
    created_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'cls-s5',
    institution_id: 'inst-001',
    academic_year_id: 'ay-2026',
    name: 'Senior Five (S.5)',
    level: 5,
    type: 'A-Level',
    capacity: 80,
    created_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'cls-s6',
    institution_id: 'inst-001',
    academic_year_id: 'ay-2026',
    name: 'Senior Six (S.6 Candidates)',
    level: 6,
    type: 'A-Level',
    capacity: 75,
    created_at: '2026-01-01T00:00:00Z',
  },
]

export const DEMO_STREAMS: Stream[] = [
  { id: 'str-s1-a', institution_id: 'inst-001', class_id: 'cls-s1', name: 'Stream Blue (North)', created_at: '2026-01-01T00:00:00Z' },
  { id: 'str-s1-b', institution_id: 'inst-001', class_id: 'cls-s1', name: 'Stream Gold (South)', created_at: '2026-01-01T00:00:00Z' },
  { id: 'str-s2-a', institution_id: 'inst-001', class_id: 'cls-s2', name: 'Stream Blue', created_at: '2026-01-01T00:00:00Z' },
  { id: 'str-s2-b', institution_id: 'inst-001', class_id: 'cls-s2', name: 'Stream Gold', created_at: '2026-01-01T00:00:00Z' },
  { id: 'str-s3-a', institution_id: 'inst-001', class_id: 'cls-s3', name: 'Stream Blue', created_at: '2026-01-01T00:00:00Z' },
  { id: 'str-s4-a', institution_id: 'inst-001', class_id: 'cls-s4', name: 'Stream Blue (Exam)', created_at: '2026-01-01T00:00:00Z' },
]

export const DEMO_SUBJECTS: Subject[] = [
  { id: 'sub-eng', institution_id: 'inst-001', name: 'English Language', code: 'ENG101', type: 'theory', is_elective: false, created_at: '2026-01-01T00:00:00Z' },
  { id: 'sub-mat', institution_id: 'inst-001', name: 'Mathematics', code: 'MTH101', type: 'theory', is_elective: false, created_at: '2026-01-01T00:00:00Z' },
  { id: 'sub-phy', institution_id: 'inst-001', name: 'Physics', code: 'PHY101', type: 'practical', is_elective: false, created_at: '2026-01-01T00:00:00Z' },
  { id: 'sub-che', institution_id: 'inst-001', name: 'Chemistry', code: 'CHM101', type: 'practical', is_elective: false, created_at: '2026-01-01T00:00:00Z' },
  { id: 'sub-bio', institution_id: 'inst-001', name: 'Biology', code: 'BIO101', type: 'practical', is_elective: false, created_at: '2026-01-01T00:00:00Z' },
  { id: 'sub-geo', institution_id: 'inst-001', name: 'Geography', code: 'GEO101', type: 'theory', is_elective: false, created_at: '2026-01-01T00:00:00Z' },
  { id: 'sub-his', institution_id: 'inst-001', name: 'History & Political Education', code: 'HIS101', type: 'theory', is_elective: false, created_at: '2026-01-01T00:00:00Z' },
  { id: 'sub-cre', institution_id: 'inst-001', name: 'Christian Religious Education', code: 'CRE101', type: 'theory', is_elective: true, created_at: '2026-01-01T00:00:00Z' },
  { id: 'sub-ict', institution_id: 'inst-001', name: 'ICT / Computer Studies', code: 'ICT101', type: 'practical', is_elective: true, created_at: '2026-01-01T00:00:00Z' },
  { id: 'sub-ent', institution_id: 'inst-001', name: 'Entrepreneurship Education', code: 'ENT101', type: 'theory', is_elective: true, created_at: '2026-01-01T00:00:00Z' },
  { id: 'sub-lug', institution_id: 'inst-001', name: 'Luganda Language & Literature', code: 'LUG101', type: 'theory', is_elective: true, created_at: '2026-01-01T00:00:00Z' },
]

export const DEMO_STAFF: Staff[] = [
  {
    id: 'stf-001',
    institution_id: 'inst-001',
    user_id: 'usr-admin',
    staff_number: 'STF/2022/001',
    first_name: 'Dr. Joseph',
    last_name: 'Muwanga',
    gender: 'male',
    phone: '+256 772 112233',
    email: 'headteacher@kampalamodel.sc.ug',
    position: 'Head Teacher / Principal',
    employment_type: 'full_time',
    qualification: 'PhD in Educational Management (Makerere Univ)',
    status: 'active',
    created_at: '2022-01-15T00:00:00Z',
  },
  {
    id: 'stf-002',
    institution_id: 'inst-001',
    user_id: 'usr-deputy',
    staff_number: 'STF/2022/002',
    first_name: 'Sarah',
    last_name: 'Nalubega',
    gender: 'female',
    phone: '+256 701 445566',
    email: 'deputy@kampalamodel.sc.ug',
    position: 'Deputy Head Teacher (Academics)',
    employment_type: 'full_time',
    qualification: 'M.Ed Curriculum & Instruction (Kyambogo Univ)',
    status: 'active',
    created_at: '2022-01-15T00:00:00Z',
  },
  {
    id: 'stf-003',
    institution_id: 'inst-001',
    user_id: 'usr-teacher',
    staff_number: 'STF/2023/014',
    first_name: 'Emmanuel',
    last_name: 'Okello',
    gender: 'male',
    phone: '+256 782 889900',
    email: 'e.okello@kampalamodel.sc.ug',
    position: 'Senior Mathematics & Physics Teacher',
    employment_type: 'full_time',
    qualification: 'B.Sc with Education (MUK)',
    status: 'active',
    created_at: '2023-02-01T00:00:00Z',
  },
  {
    id: 'stf-004',
    institution_id: 'inst-001',
    user_id: 'usr-bursar',
    staff_number: 'STF/2021/008',
    first_name: 'Grace',
    last_name: 'Atuhaire',
    gender: 'female',
    phone: '+256 752 334455',
    email: 'bursar@kampalamodel.sc.ug',
    position: 'Chief Bursar & Accountant',
    employment_type: 'full_time',
    qualification: 'CPA (Uganda), B.Com Finance',
    status: 'active',
    created_at: '2021-06-01T00:00:00Z',
  },
  {
    id: 'stf-005',
    institution_id: 'inst-001',
    staff_number: 'STF/2024/022',
    first_name: 'Sister Mary',
    last_name: 'Namaganda',
    gender: 'female',
    phone: '+256 774 991122',
    email: 'nurse@kampalamodel.sc.ug',
    position: 'School Health Officer / Senior Nurse',
    employment_type: 'full_time',
    qualification: 'Registered Comprehensive Nurse (UNMC)',
    status: 'active',
    created_at: '2024-01-10T00:00:00Z',
  },
]

export const DEMO_PARENTS: Parent[] = [
  {
    id: 'par-001',
    institution_id: 'inst-001',
    full_name: 'Eng. Patrick Kigozi',
    phone: '+256 772 400111',
    email: 'pkigozi@gmail.com',
    address: 'Plot 18, Bukoto Crescent, Kampala',
    occupation: 'Civil Engineer / Contractor',
    created_at: '2024-01-10T00:00:00Z',
  },
  {
    id: 'par-002',
    institution_id: 'inst-001',
    full_name: 'Dr. Rebecca Nakimera',
    phone: '+256 701 500222',
    email: 'r.nakimera@mulago.org',
    address: 'Naguru Hill Drive, Kampala',
    occupation: 'Consultant Pediatrician',
    created_at: '2024-01-12T00:00:00Z',
  },
  {
    id: 'par-003',
    institution_id: 'inst-001',
    full_name: 'Mr. Moses Ssempa',
    phone: '+256 782 600333',
    email: 'moses.ssempa@kcca.go.ug',
    address: 'Ntinda Ministers Village, Kampala',
    occupation: 'Senior Urban Planner (KCCA)',
    created_at: '2025-01-08T00:00:00Z',
  },
  {
    id: 'par-004',
    institution_id: 'inst-001',
    full_name: 'Ms. Florence Akello',
    phone: '+256 754 700444',
    email: 'florence.akello@stanbic.com',
    address: 'Kyanja Ring Road, Kampala',
    occupation: 'Commercial Banking Lead',
    created_at: '2025-01-15T00:00:00Z',
  },
]

export const DEMO_STUDENTS: Student[] = [
  {
    id: 'stu-001',
    institution_id: 'inst-001',
    admission_number: 'KMHS/2026/001',
    first_name: 'Brian',
    last_name: 'Kigozi',
    middle_name: 'Paul',
    date_of_birth: '2011-04-12',
    gender: 'male',
    nationality: 'Ugandan',
    address: 'Bukoto, Kampala',
    phone: '+256 772 400111',
    previous_school: 'Kampala Parents School (PLE: Agg 4)',
    admission_date: '2026-01-20',
    status: 'active',
    allergies: 'Peanuts',
    blood_group: 'O+',
    emergency_contact_name: 'Eng. Patrick Kigozi (Father)',
    emergency_contact_phone: '+256 772 400111',
    current_class_id: 'cls-s1',
    current_stream_id: 'str-s1-a',
    created_at: '2026-01-20T09:00:00Z',
    updated_at: '2026-01-20T09:00:00Z',
  },
  {
    id: 'stu-002',
    institution_id: 'inst-001',
    admission_number: 'KMHS/2026/002',
    first_name: 'Esther',
    last_name: 'Namubiru',
    middle_name: 'Grace',
    date_of_birth: '2011-07-25',
    gender: 'female',
    nationality: 'Ugandan',
    address: 'Naguru, Kampala',
    phone: '+256 701 500222',
    previous_school: 'Greenhill Academy (PLE: Agg 5)',
    admission_date: '2026-01-20',
    status: 'active',
    allergies: 'None',
    blood_group: 'A+',
    emergency_contact_name: 'Dr. Rebecca Nakimera (Mother)',
    emergency_contact_phone: '+256 701 500222',
    current_class_id: 'cls-s1',
    current_stream_id: 'str-s1-a',
    created_at: '2026-01-20T09:30:00Z',
    updated_at: '2026-01-20T09:30:00Z',
  },
  {
    id: 'stu-003',
    institution_id: 'inst-001',
    admission_number: 'KMHS/2025/088',
    first_name: 'Trevor',
    last_name: 'Ssempa',
    middle_name: 'David',
    date_of_birth: '2010-02-18',
    gender: 'male',
    nationality: 'Ugandan',
    address: 'Ntinda, Kampala',
    phone: '+256 782 600333',
    previous_school: 'City Parents School',
    admission_date: '2025-01-18',
    status: 'active',
    blood_group: 'B+',
    emergency_contact_name: 'Mr. Moses Ssempa (Father)',
    emergency_contact_phone: '+256 782 600333',
    current_class_id: 'cls-s2',
    current_stream_id: 'str-s2-a',
    created_at: '2025-01-18T10:00:00Z',
    updated_at: '2025-01-18T10:00:00Z',
  },
  {
    id: 'stu-004',
    institution_id: 'inst-001',
    admission_number: 'KMHS/2024/045',
    first_name: 'Diana',
    last_name: 'Akello',
    middle_name: 'Patricia',
    date_of_birth: '2009-09-05',
    gender: 'female',
    nationality: 'Ugandan',
    address: 'Kyanja, Kampala',
    phone: '+256 754 700444',
    previous_school: 'Victoria Nile Primary School, Jinja',
    admission_date: '2024-01-15',
    status: 'active',
    blood_group: 'AB+',
    emergency_contact_name: 'Ms. Florence Akello (Mother)',
    emergency_contact_phone: '+256 754 700444',
    current_class_id: 'cls-s3',
    current_stream_id: 'str-s3-a',
    created_at: '2024-01-15T11:00:00Z',
    updated_at: '2024-01-15T11:00:00Z',
  },
  {
    id: 'stu-005',
    institution_id: 'inst-001',
    admission_number: 'KMHS/2023/012',
    first_name: 'Joshua',
    last_name: 'Mugisha',
    middle_name: 'Ivan',
    date_of_birth: '2008-11-14',
    gender: 'male',
    nationality: 'Ugandan',
    address: 'Naalya, Kampala',
    phone: '+256 772 888777',
    admission_date: '2023-01-22',
    status: 'active',
    emergency_contact_name: 'Frank Mugisha (Guardian)',
    emergency_contact_phone: '+256 772 888777',
    current_class_id: 'cls-s4',
    current_stream_id: 'str-s4-a',
    created_at: '2023-01-22T08:00:00Z',
    updated_at: '2023-01-22T08:00:00Z',
  },
  {
    id: 'stu-006',
    institution_id: 'inst-001',
    admission_number: 'KMHS/2026/006',
    first_name: 'Mercy',
    last_name: 'Achan',
    middle_name: 'Lillian',
    date_of_birth: '2011-08-30',
    gender: 'female',
    nationality: 'Ugandan',
    address: 'Kololo, Kampala',
    admission_date: '2026-01-21',
    status: 'active',
    current_class_id: 'cls-s1',
    current_stream_id: 'str-s1-b',
    created_at: '2026-01-21T09:00:00Z',
    updated_at: '2026-01-21T09:00:00Z',
  },
]

export const DEMO_PARENT_STUDENTS: ParentStudent[] = [
  { id: 'ps-1', parent_id: 'par-001', student_id: 'stu-001', relationship: 'Father', is_primary_contact: true, is_emergency_contact: true },
  { id: 'ps-2', parent_id: 'par-002', student_id: 'stu-002', relationship: 'Mother', is_primary_contact: true, is_emergency_contact: true },
  { id: 'ps-3', parent_id: 'par-003', student_id: 'stu-003', relationship: 'Father', is_primary_contact: true, is_emergency_contact: true },
  { id: 'ps-4', parent_id: 'par-004', student_id: 'stu-004', relationship: 'Mother', is_primary_contact: true, is_emergency_contact: true },
]

export const DEMO_GRADING_SYSTEM: GradingSystem = {
  id: 'grd-uneb-olevel',
  institution_id: 'inst-001',
  name: 'UNEB O-Level Standards (D1 to F9)',
  is_default: true,
  scales: [
    { id: 'sc-1', grading_system_id: 'grd-uneb-olevel', grade: 'D1 (Distinction 1)', min_score: 80, max_score: 100, points: 1, description: 'Exceptional Performance' },
    { id: 'sc-2', grading_system_id: 'grd-uneb-olevel', grade: 'D2 (Distinction 2)', min_score: 70, max_score: 79,  points: 2, description: 'Very Good' },
    { id: 'sc-3', grading_system_id: 'grd-uneb-olevel', grade: 'C3 (Credit 3)',       min_score: 65, max_score: 69,  points: 3, description: 'Good' },
    { id: 'sc-4', grading_system_id: 'grd-uneb-olevel', grade: 'C4 (Credit 4)',       min_score: 60, max_score: 64,  points: 4, description: 'Satisfactory Credit' },
    { id: 'sc-5', grading_system_id: 'grd-uneb-olevel', grade: 'C5 (Credit 5)',       min_score: 55, max_score: 59,  points: 5, description: 'Average Credit' },
    { id: 'sc-6', grading_system_id: 'grd-uneb-olevel', grade: 'C6 (Credit 6)',       min_score: 50, max_score: 54,  points: 6, description: 'Pass Credit' },
    { id: 'sc-7', grading_system_id: 'grd-uneb-olevel', grade: 'P7 (Pass 7)',         min_score: 45, max_score: 49,  points: 7, description: 'Marginal Pass' },
    { id: 'sc-8', grading_system_id: 'grd-uneb-olevel', grade: 'P8 (Pass 8)',         min_score: 40, max_score: 44,  points: 8, description: 'Weak Pass' },
    { id: 'sc-9', grading_system_id: 'grd-uneb-olevel', grade: 'F9 (Fail 9)',         min_score: 0,  max_score: 39,  points: 9, description: 'Ungraded / Fail' },
  ],
}

export const DEMO_EXAMS: Exam[] = [
  {
    id: 'ex-001',
    institution_id: 'inst-001',
    name: 'Term 1 Mid-Term Examination - Mathematics',
    exam_type: 'midterm',
    class_id: 'cls-s1',
    subject_id: 'sub-mat',
    term_id: 'term-1-2026',
    academic_year_id: 'ay-2026',
    date: '2026-03-18',
    max_marks: 100,
    pass_marks: 50,
    weight_percentage: 30,
    created_at: '2026-03-01T00:00:00Z',
  },
  {
    id: 'ex-002',
    institution_id: 'inst-001',
    name: 'Term 1 Mid-Term Examination - English Language',
    exam_type: 'midterm',
    class_id: 'cls-s1',
    subject_id: 'sub-eng',
    term_id: 'term-1-2026',
    academic_year_id: 'ay-2026',
    date: '2026-03-19',
    max_marks: 100,
    pass_marks: 50,
    weight_percentage: 30,
    created_at: '2026-03-01T00:00:00Z',
  },
  {
    id: 'ex-003',
    institution_id: 'inst-001',
    name: 'Term 1 Mid-Term Examination - Physics',
    exam_type: 'midterm',
    class_id: 'cls-s1',
    subject_id: 'sub-phy',
    term_id: 'term-1-2026',
    academic_year_id: 'ay-2026',
    date: '2026-03-20',
    max_marks: 100,
    pass_marks: 50,
    weight_percentage: 30,
    created_at: '2026-03-01T00:00:00Z',
  },
]

export const DEMO_MARKS: StudentMark[] = [
  { id: 'mk-001', exam_id: 'ex-001', student_id: 'stu-001', marks_obtained: 88, grade: 'D1 (Distinction 1)', remarks: 'Excellent computational problem solving', entered_by: 'stf-003', entered_at: '2026-03-22T10:00:00Z', is_published: true },
  { id: 'mk-002', exam_id: 'ex-001', student_id: 'stu-002', marks_obtained: 94, grade: 'D1 (Distinction 1)', remarks: 'Outstanding analytical precision', entered_by: 'stf-003', entered_at: '2026-03-22T10:00:00Z', is_published: true },
  { id: 'mk-003', exam_id: 'ex-001', student_id: 'stu-006', marks_obtained: 68, grade: 'C3 (Credit 3)', remarks: 'Good grasp of algebra, needs revision on geometry', entered_by: 'stf-003', entered_at: '2026-03-22T10:00:00Z', is_published: true },

  { id: 'mk-004', exam_id: 'ex-002', student_id: 'stu-001', marks_obtained: 76, grade: 'D2 (Distinction 2)', remarks: 'Strong essay writing and comprehension', entered_by: 'stf-002', entered_at: '2026-03-23T11:00:00Z', is_published: true },
  { id: 'mk-005', exam_id: 'ex-002', student_id: 'stu-002', marks_obtained: 85, grade: 'D1 (Distinction 1)', remarks: 'Expressive vocabulary and impeccable grammar', entered_by: 'stf-002', entered_at: '2026-03-23T11:00:00Z', is_published: true },
  { id: 'mk-006', exam_id: 'ex-002', student_id: 'stu-006', marks_obtained: 72, grade: 'D2 (Distinction 2)', remarks: 'Well structured literature summary', entered_by: 'stf-002', entered_at: '2026-03-23T11:00:00Z', is_published: true },
]

export const DEMO_FEE_STRUCTURES: FeeStructure[] = [
  { id: 'fee-tui-s1', institution_id: 'inst-001', academic_year_id: 'ay-2026', term_id: 'term-1-2026', class_id: 'cls-s1', name: 'Tuition Fee (Day Scholar)', amount: 950000, currency: 'UGX', fee_type: 'tuition', is_mandatory: true, created_at: '2026-01-05T00:00:00Z' },
  { id: 'fee-dev', institution_id: 'inst-001', academic_year_id: 'ay-2026', term_id: 'term-1-2026', name: 'School Development & Science Lab Levy', amount: 150000, currency: 'UGX', fee_type: 'other', is_mandatory: true, created_at: '2026-01-05T00:00:00Z' },
  { id: 'fee-meals', institution_id: 'inst-001', academic_year_id: 'ay-2026', term_id: 'term-1-2026', name: 'Hot Lunch & Refreshment Program', amount: 300000, currency: 'UGX', fee_type: 'meals', is_mandatory: false, created_at: '2026-01-05T00:00:00Z' },
  { id: 'fee-uniform', institution_id: 'inst-001', academic_year_id: 'ay-2026', name: 'New Student Uniform & Sports Kit (3 Sets)', amount: 280000, currency: 'UGX', fee_type: 'uniform', is_mandatory: true, created_at: '2026-01-05T00:00:00Z' },
  { id: 'fee-board', institution_id: 'inst-001', academic_year_id: 'ay-2026', term_id: 'term-1-2026', name: 'Full Boarding & Accommodation', amount: 850000, currency: 'UGX', fee_type: 'boarding', is_mandatory: false, created_at: '2026-01-05T00:00:00Z' },
]

export const DEMO_INVOICES: StudentInvoice[] = [
  {
    id: 'inv-001',
    institution_id: 'inst-001',
    student_id: 'stu-001',
    academic_year_id: 'ay-2026',
    term_id: 'term-1-2026',
    total_amount: 1680000, // Tuition (950k) + Dev (150k) + Meals (300k) + Uniform (280k)
    total_paid: 1680000,
    balance: 0,
    status: 'paid',
    due_date: '2026-02-15',
    created_at: '2026-01-20T10:00:00Z',
    items: [
      { id: 'ii-1', invoice_id: 'inv-001', fee_structure_id: 'fee-tui-s1', description: 'Tuition Fee (Day Scholar)', amount: 950000 },
      { id: 'ii-2', invoice_id: 'inv-001', fee_structure_id: 'fee-dev', description: 'School Development & Science Lab Levy', amount: 150000 },
      { id: 'ii-3', invoice_id: 'inv-001', fee_structure_id: 'fee-meals', description: 'Hot Lunch & Refreshment Program', amount: 300000 },
      { id: 'ii-4', invoice_id: 'inv-001', fee_structure_id: 'fee-uniform', description: 'New Student Uniform & Sports Kit', amount: 280000 },
    ],
  },
  {
    id: 'inv-002',
    institution_id: 'inst-001',
    student_id: 'stu-002',
    academic_year_id: 'ay-2026',
    term_id: 'term-1-2026',
    total_amount: 1680000,
    total_paid: 1000000,
    balance: 680000,
    status: 'partial',
    due_date: '2026-02-15',
    created_at: '2026-01-20T10:00:00Z',
    items: [
      { id: 'ii-5', invoice_id: 'inv-002', fee_structure_id: 'fee-tui-s1', description: 'Tuition Fee (Day Scholar)', amount: 950000 },
      { id: 'ii-6', invoice_id: 'inv-002', fee_structure_id: 'fee-dev', description: 'School Development & Science Lab Levy', amount: 150000 },
      { id: 'ii-7', invoice_id: 'inv-002', fee_structure_id: 'fee-meals', description: 'Hot Lunch & Refreshment Program', amount: 300000 },
      { id: 'ii-8', invoice_id: 'inv-002', fee_structure_id: 'fee-uniform', description: 'New Student Uniform & Sports Kit', amount: 280000 },
    ],
  },
  {
    id: 'inv-003',
    institution_id: 'inst-001',
    student_id: 'stu-003',
    academic_year_id: 'ay-2026',
    term_id: 'term-1-2026',
    total_amount: 1400000,
    total_paid: 0,
    balance: 1400000,
    status: 'outstanding',
    due_date: '2026-02-15',
    created_at: '2026-01-20T10:00:00Z',
    items: [
      { id: 'ii-9', invoice_id: 'inv-003', description: 'Senior Two Term 1 Tuition', amount: 950000 },
      { id: 'ii-10', invoice_id: 'inv-003', description: 'School Development Levy', amount: 150000 },
      { id: 'ii-11', invoice_id: 'inv-003', description: 'Meals Program', amount: 300000 },
    ],
  },
]

export const DEMO_PAYMENTS: Payment[] = [
  {
    id: 'pay-001',
    institution_id: 'inst-001',
    invoice_id: 'inv-001',
    student_id: 'stu-001',
    amount: 1680000,
    currency: 'UGX',
    payment_method: 'Stanbic Bank (Bank Deposit Slip)',
    reference_number: 'DEP-SB-982341',
    received_by: 'stf-004',
    notes: 'Paid in full at Stanbic Garden City Branch',
    payment_date: '2026-01-22',
    created_at: '2026-01-22T14:30:00Z',
    receipt: {
      id: 'rcp-001',
      payment_id: 'pay-001',
      receipt_number: 'RCP-2026-00014',
      issued_at: '2026-01-22T14:30:00Z',
      issued_by: 'Grace Atuhaire (Bursar)',
    },
  },
  {
    id: 'pay-002',
    institution_id: 'inst-001',
    invoice_id: 'inv-002',
    student_id: 'stu-002',
    amount: 1000000,
    currency: 'UGX',
    payment_method: 'MTN Mobile Money',
    reference_number: 'MOMO-TX-4482910',
    received_by: 'stf-004',
    notes: 'First installment payment. Balance UGX 680,000 due before mid-terms',
    payment_date: '2026-01-25',
    created_at: '2026-01-25T11:15:00Z',
    receipt: {
      id: 'rcp-002',
      payment_id: 'pay-002',
      receipt_number: 'RCP-2026-00029',
      issued_at: '2026-01-25T11:15:00Z',
      issued_by: 'Grace Atuhaire (Bursar)',
    },
  },
]

export const DEMO_ATTENDANCE_SESSIONS: AttendanceSession[] = [
  {
    id: 'att-sess-001',
    institution_id: 'inst-001',
    class_id: 'cls-s1',
    stream_id: 'str-s1-a',
    date: '2026-08-24',
    period: 'Morning Roll Call',
    term_id: 'term-1-2026',
    taken_by: 'stf-003',
    created_at: '2026-08-24T08:15:00Z',
  },
]

export const DEMO_ATTENDANCE_RECORDS: AttendanceRecord[] = [
  { id: 'att-rec-001', session_id: 'att-sess-001', student_id: 'stu-001', status: 'present', created_at: '2026-08-24T08:15:00Z' },
  { id: 'att-rec-002', session_id: 'att-sess-001', student_id: 'stu-002', status: 'present', created_at: '2026-08-24T08:15:00Z' },
  { id: 'att-rec-003', session_id: 'att-sess-001', student_id: 'stu-006', status: 'late', notes: 'Arrived at 8:25 AM due to traffic', created_at: '2026-08-24T08:15:00Z' },
]

export const DEMO_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'aud-001',
    institution_id: 'inst-001',
    user_id: 'usr-admin',
    action: 'Student Admission Created',
    table_name: 'students',
    record_id: 'stu-001',
    new_values: { admission_number: 'KMHS/2026/001', full_name: 'Brian Kigozi', class: 'Senior One' },
    ip_address: '197.239.4.12 (Kampala, Uganda)',
    created_at: '2026-01-20T09:00:00Z',
  },
  {
    id: 'aud-002',
    institution_id: 'inst-001',
    user_id: 'usr-bursar',
    action: 'Payment Recorded & Receipt Issued',
    table_name: 'payments',
    record_id: 'pay-001',
    new_values: { receipt_number: 'RCP-2026-00014', amount: 'UGX 1,680,000', student: 'Brian Kigozi' },
    ip_address: '197.239.4.12 (Kampala, Uganda)',
    created_at: '2026-01-22T14:30:00Z',
  },
  {
    id: 'aud-003',
    institution_id: 'inst-001',
    user_id: 'usr-teacher',
    action: 'Midterm Examination Marks Published',
    table_name: 'student_marks',
    record_id: 'ex-001',
    new_values: { exam: 'Mid-Term Mathematics S.1', records_entered: 3 },
    ip_address: '41.210.140.50 (Kampala, Uganda)',
    created_at: '2026-03-22T10:00:00Z',
  },
]

export const DEMO_AUTH_USERS: Record<string, AuthUser> = {
  admin: {
    id: 'usr-admin',
    email: 'admin@kampalamodel.sc.ug',
    role: 'school_admin',
    institution_id: 'inst-001',
    profile: {
      id: 'usr-admin',
      full_name: 'Dr. Joseph Muwanga',
      phone: '+256 772 112233',
      address: 'Kampala, Uganda',
      created_at: '2022-01-15T00:00:00Z',
    },
    institution: DEMO_INSTITUTIONS[0],
  },
  teacher: {
    id: 'usr-teacher',
    email: 'teacher@kampalamodel.sc.ug',
    role: 'teacher',
    institution_id: 'inst-001',
    profile: {
      id: 'usr-teacher',
      full_name: 'Mr. Emmanuel Okello',
      phone: '+256 782 889900',
      address: 'Kampala, Uganda',
      created_at: '2023-02-01T00:00:00Z',
    },
    institution: DEMO_INSTITUTIONS[0],
  },
  bursar: {
    id: 'usr-bursar',
    email: 'bursar@kampalamodel.sc.ug',
    role: 'bursar',
    institution_id: 'inst-001',
    profile: {
      id: 'usr-bursar',
      full_name: 'Grace Atuhaire',
      phone: '+256 752 334455',
      address: 'Kampala, Uganda',
      created_at: '2021-06-01T00:00:00Z',
    },
    institution: DEMO_INSTITUTIONS[0],
  },
  parent: {
    id: 'usr-parent',
    email: 'parent@kampalamodel.sc.ug',
    role: 'parent',
    institution_id: 'inst-001',
    profile: {
      id: 'usr-parent',
      full_name: 'Eng. Patrick Kigozi',
      phone: '+256 772 400111',
      address: 'Plot 18, Bukoto Crescent, Kampala',
      created_at: '2024-01-10T00:00:00Z',
    },
    institution: DEMO_INSTITUTIONS[0],
  },
  student: {
    id: 'usr-student',
    email: 'student@kampalamodel.sc.ug',
    role: 'student',
    institution_id: 'inst-001',
    profile: {
      id: 'usr-student',
      full_name: 'Brian Kigozi (S.1)',
      phone: '+256 772 400111',
      address: 'Bukoto, Kampala',
      created_at: '2026-01-20T00:00:00Z',
    },
    institution: DEMO_INSTITUTIONS[0],
  },
}
